version: "3.9"
services:
  drones:
    image: drones
    ports:
      - ${DRONES_PORT}:${DRONES_PORT}
    depends_on:
      - db

  db:
    container_name: ${POSTGRES_CONTAINER:-db}
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PG_DATA: /var/lib/postgresql/data/pgdata
    ports:
      - ${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}
    command:
      - "-p ${POSTGRES_PORT:-5432}"
    volumes:
      - ./postgres:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus:v2.21.0
    ports:
      - ${PROMETHEUS_PORT:-9090}:9090
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
    depends_on:
      - drones
