server:
  port: ${DRONES_PORT}

spring:
  flyway:
    baseline-on-migrate: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_CONTAINER}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  aop:
    proxy-target-class: true

management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus


