spring:
  flyway:
    baseline-on-migrate: true
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: postgres
  aop:
    proxy-target-class: true

management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus



